### ISSUE TITLE
Should I use checkSubscribed() method?

### ISSUE THREAD

**Issue by rdcoder33** [dooboolab/flutter_inapp_purchase#121]
version: Latest

 So, `FlutterInappPurchase.instance.checkSubscribed();` docs says 

> Check if a subscription is active on Android and iOS.
> This is a quick and dirty way to check if a subscription is active. It is highly recommended to do server-side validation for all subscriptions. This method is NOT secure and untested in production.

I want to know how "DIRTY" this method is in the production environment. Because checking if the user has an active subscription on server-side is a lot of work especially when you have a month, 3 months,6 months and yearly plan.

And if I should not use this method than any suggestions on how to validate if a user is `subscribed` in a `flutter-firebase` app.

**Comment by hyochan** [comment]
I used to validate using [this](https://github.com/voltrue2/in-app-purchase)

**Comment by rdcoder33** [comment]
> I used to validate using [this](https://github.com/voltrue2/in-app-purchase)

How can I use this in Flutter? I don't know node.js, are you suggesting me to use this as firebase-function?

**Comment by hyochan** [comment]
@rdcoder33 You can use firebase-functions or nodejs. It would depend on what dev stacks you are bringing for production.

**Comment by JayM96** [comment]
Hello @hyochan @rdcoder33 @dooboolab how can i check if i any subscription is active already or not?

Otherwise can i have any param in purchasehistory which can give me the details of the transactionexpiry or plan validity in time units?

Is it possible to check that my plan is active or not anyway from this package methods?

Otherwise can you suggest a minimal code to find out the best approach to find the subscription expiry time or list of active subscriptions in flutter in app purchase?

This would be a huge help from you.

Thanks.
