### ISSUE TITLE
Apple rejected our app, "An unknown or unexpected error has occured. Please try again later." (screenshot)

### ISSUE THREAD

**Issue by phuc-koli** [dooboolab/flutter_inapp_purchase#156]
Please note that we can not reproduce this bug on our iPhone and iPad devices. Apple tested and rejected (on their iPad wifi iOS 13.3) even when our app does not support iPad.

### Tested environment (Emulator? Real Device?): real device

![image](https://user-images.githubusercontent.com/55618058/73662081-c7a5e700-46cd-11ea-8cff-4a1b39fe2c72.png)

**Comment by srsudar** [comment]
What was the cause here?

**Comment by drewjbartlett** [comment]
Having the same issue and can't figure out what the cause is. I'm able to get this fully working on TestFlight but for some reason Apple is having issues when reviewing.

**Comment by srsudar** [comment]
I saw this once, but it went away. After Apple said it hadn't worked, I tried again on my device, and I saw a similar error (your case might be different, but I'd still try this fix).

I went to the In-App Purchases section of the Apple website and saw that the items said "developer action needed" or something similar. To reset them I changed the description slightly (just enough so that the save button became enabled), and then I clicked save. For whatever reason this seemed to reset the bad state and I didn't have the problem again.

I had to do this twice in taking my app from development to production. There was no indication from Apple as to what triggered it. Very annoying. Not sure if it is the same for you, but I'd suggest editing the descriptions slightly and re-saving them, then submitting again.
