### ISSUE TITLE
ios problem 

### ISSUE THREAD

**Issue by hsnbsst** [dooboolab/flutter_inapp_purchase#170]
### Steps to reproduce the behavior

`purchase-error: responseCode: null, debugMessage: SKPaymentTransactionStateFailed, code: E_UNKNOWN, message: An unknown or unexpected error has occured. Please try again later.`

**Comment by TruongKhanhHung** [comment]
I also had the same problem. Did you find a solution?
<img width="1394" alt="Screen Shot 2020-04-04 at 15 08 24" src="https://user-images.githubusercontent.com/27353944/78516377-86bc7280-77e3-11ea-85c8-79b3e12583cd.png">

**Comment by hsnbsst** [comment]
no I couldn't find the solution

**Comment by oncul** [comment]
I have same problem, any solution ?

**Comment by hyochan** [comment]
Did it happened after requesting the purchase? `example` project seems to work fine.

**Comment by TruongKhanhHung** [comment]
> Did it happened after requesting the purchase? `example` project seems to work fine.

Yeah, this happens when the call method request "purchase".

Since updating to Xcode 11.4, Flutter 1.12 hotfix 9, it no longer works.

**Comment by oncul** [comment]
I test on ios 12 real device its working properly but on ios 13.4 its not working.

**Comment by TruongKhanhHung** [comment]
> I test on ios 12 real device its working properly but on ios 13.4 its not working.

Oh yes, I'm using a device running iOS 13.4

**Comment by oncul** [comment]
Is there any fix ?

**Comment by hyochan** [comment]
Try 2.1.5. I published fixes in #176

**Comment by hsnbsst** [comment]
Although I used 2.1.5, it didn't improve @hyochan

**Comment by umaqs** [comment]
I have the same problem with `requestPurchase()` in production (TestFlight) app. 
AdHoc builds are working fine however.

**Comment by ipolx** [comment]
Any updates on this issue? version 2.2.0. I'm getting this error for consumable products

**Comment by eduardothiesen** [comment]
I'm experiencing the same issue. 

responseCode: null, debugMessage: SKPaymentTransactionStateFailed, code: E_UNKNOWN, message: An unknown or unexpected error has occured. Please try again later.

Flutter 1.19.0
Dart 2.9.0 
flutter_inapp_purchase: ^2.2.0

**Comment by saarikivit** [comment]
This is still a problem

**Comment by build-mobility** [comment]
Yes, I am getting the same

**Comment by ankitch29** [comment]
For me, It's happening if user purchased a subscription already and again request a subscription.

**Comment by Nikoyan-V** [comment]
Is there any updates related to this issue?. I am using  flutter_inapp_purchase 5.1.2

**Comment by chhsh122** [comment]
. I am using flutter_inapp_purchase 5.3.1 .have same problem

**Comment by giantss** [comment]
I am using flutter_inapp_purchase 5.4.2 .have same problem.

For me, It's happening if user purchased a subscription already and again request a subscription.

**Comment by taosif7-dreamorbit** [comment]
Facing same issue on v5.4.2 where a user purchases subscription is still available. Is this addressed on newer versions? @hyochan ?

**Comment by giantss** [comment]
This error is bound to occur in this environment.
Reproduction process:

1. Subscription successful.
2. (Sandbox) Unsubscribe.
3. Wait for the server status to unsubscribe (about 2-3s later), and subscribe again in the app.
4. Error SKPaymentTransactionStateFailed

For the above renewal process, the server will receive the renewal notification normally, but the client will report the error SKPaymentTransactionStateFailed. Our current solution is to handle it separately for the ios platform in the error callback purchaseError.
The processing logic is: If this happens, we add a loading UI, wait for 10s (the time when the server receives Apple's renewal message is not sure, probably between 2s and 8s), and then use its own server api interface Check the current user's subscription status. If the subscription is successful, it will jump to the success interface, otherwise an error will be reported.
@taosif7-dreamorbit

**Comment by anilthummar** [comment]
@oncul @eduardothiesen @umaqs @giantss 
still getting error on live ios app , when i try to purchase my service  the default payment ios dialog dismiss and getting below error in flutter side.
`purchase-error F: responseCode: null, debugMessage: SKPaymentTransactionStateFailed, code: E_USER_CANCELLED, message: Cancelled.`
