### ISSUE TITLE
E_USER_CANCELLED when user taps "OK" when being informed that they are already subscribed

### ISSUE THREAD

**Issue by lukepighetti** [dooboolab/flutter_inapp_purchase#22]
does iOS expose a way to tell when a user taps "OK" when being informed that they are already subscribed?

**Comment by lukepighetti** [comment]
Trying to find out how to discern between cancelled purchase and click "OK" when being told that they already purchased :)

**Comment by JJMoon** [comment]
I don't get the issue here.
If a user sees 'OK' on already purchased items, why don't you just ignore it?
I guess it's not on the IAP, but on the UI logic itself.

Anyway, this might help.

https://developer.apple.com/library/archive/documentation/NetworkingInternet/Conceptual/StoreKitGuide/Introduction.html#//apple_ref/doc/uid/TP40008267-CH1-SW1

**Comment by lukepighetti** [comment]
If Apple responds the same for purchase cancelled vs already-subscribed-click-OK, then this should definitely be closed. Can someone confirm that there is only one response from Apple services?

**Comment by yasirsalim22** [comment]
> Trying to find out how to discern between cancelled purchase and click "OK" when being told that they already purchased :)

I am getting the same E_USER_CANCELLED if already purchased. So I cannot make this thing if user press cancel or user press ok.

@lukepighetti  @JJMoon

**Comment by hyochan** [comment]
`2.0.0+` has raised today. Please feel free to reopen after trying out `2.0.0+5` or above.
