### ISSUE TITLE
Suggestion: Add detailed blog on how to use the plugin in README

### ISSUE THREAD

**Issue by varunkamani** [dooboolab/flutter_inapp_purchase#234]
I have written a blog post on how to add subscriptions in-app purchases in Flutter using this plugin.

[How to Implement Subscriptions In-App Purchase in Flutter](https://medium.com/bosc-tech-labs-private-limited/how-to-implement-subscriptions-in-app-purchase-in-flutter-7ce8906e608a)

For many people who wants to use this plugin this post will be very helpful to them to start with.

I wrote this blog after implementing the same approach in my Flutter app.

I know the doubts I faced while implementing the in-app purchase feature in my app.

Please do correct me if any information is wrong or needs improvement in the blog.

Thanks!

**Comment by dipinarora9** [comment]
Hey @varunkamani ,
I read your blog. It's awesome, great work.

But I am seeing that you are calling `finishTransaction` when the transaction state is deferred, you should NOT do that.
Deferred state may arise when the billing api is asking the user for his payment details. But that does NOT mean that the transaction is finished.

Finish transaction should only be called when the transaction state is either purchased, failed or restored.

Read more here: https://developer.apple.com/documentation/storekit/skpaymentqueue/1506003-finishtransaction

**Comment by varunkamani** [comment]
Hi @dipinarora9 
Thanks for the response.

What action should I take in the case of a `Deferred` state? Should I do nothing just like the `Purchasing` state?

This will help me to correct the blog and my existing app. 

Is there any other thing that I'm doing wrong?

Thanks.

**Comment by dipinarora9** [comment]
Yes, leaving it to nothing just like purchasing state would be ok.

And no, there is no other mistake.

**Comment by varunkamani** [comment]
Thanks.

**Comment by varunkamani** [comment]
@dipinarora9 Thanks for the feedback. I have fixed the bug. Please verify.

**Comment by varunkamani** [comment]
#264

**Comment by srsudar** [comment]
That was very helpful, thanks. I wish I'd seen this earlier! You have this block in `_getPastPurchases()`:

```
    for (var purchasedItem in purchasedItems) {
      bool isValid = false;

      if (Platform.isAndroid) {
        Map map = json.decode(purchasedItem.transactionReceipt);
          // if your app missed finishTransaction due to network or crash issue
          // finish transactins
        if (!map['acknowledged']) {
          isValid = await _verifyPurchase(purchasedItem);
          if (isValid) {
            FlutterInappPurchase.instance.finishTransaction(purchasedItem);
            _isProUser = true;
            _callProStatusChangedListeners();
          }
        } else {
          _isProUser = true;
          _callProStatusChangedListeners();
        }
      }
    }
```

I wasn't doing this, but was just checking `isAcknowledgedAndroid`. This was crashing my app, because it is `null` for subscriptions, apparently. It is set for non-consumable purchases. You can see that this is apparently by design, as it is set [here](https://github.com/dooboolab/flutter_inapp_purchase/blob/5da60a23400f2aa2d169dfd6ac76b02ae3551d16/android/src/main/java/com/dooboolab/flutterinapppurchase/AndroidInappPurchasePlugin.java#L329).

Is that expected behavior for some reason that I am missing? It surprises me. Very helpful that the plugin provides that data as a workaround, but I'm wondering if I'm missing something about subscriptions...
