### ISSUE TITLE
iOS very slow

### ISSUE THREAD

**Issue by Joyker** [dooboolab/flutter_inapp_purchase#283]
### Version of flutter_inapp_purchase
3.0.1

### Platforms you faced the error (IOS or Android or both?)
iOS
### Expected behavior
click item - get purchase dialog
### Actual behavior
click item - purchase dialog after 2-3 minutes
### Tested environment (Emulator? Real Device?)
Real device
### Steps to reproduce the behavior
follow example

**Comment by JaviCore** [comment]
Same issue here with 3.0.1
It worked fine till last week but suddenly today, when I tested my app again, it is extremely slow (minutes just to show the payment dialog). I'm guessing it is an apple problem of sorts since they lately had a sandbox maintenance and all the subsequent 14.5 updates they are doing.
