### ISSUE TITLE
Is it safe to use validateReceiptIos when validating the latest receipt from getPurchaseHistory()

### ISSUE THREAD

**Issue by vagrantrobbie** [dooboolab/flutter_inapp_purchase#40]
### Version of flutter_inapp_purchase
0.7.1

I'd like to use this on the device as sometimes the base64 string arrives at Firebase or Cloud Functions as incomplete and we receive errors trying to validate it with the /verifyReceipt endpoint. Oddly this works fine with Sandbox testers receipts and we only have incomplete strings when using Production where sometimes we are missing everything after the first / in the base64 string :(

https://developer.apple.com/library/archive/releasenotes/General/ValidateAppStoreReceipt/Chapters/ValidateRemotely.html specifically says not to check from the app, so what can we do here? Will we be denied from the store?

**Comment by dooboolab** [comment]
@vagrantrobbie Good that you've found out some information that I should write up for readme. As Apple said, it can cause the middle attack, however for things like POC app, you can still use this feature. If your app got really popular, you may structure this feature in your backend so that it can be more safely used.
