### ISSUE TITLE
getAvailablePurchases not fetching unconsumed PurchaseItem

### ISSUE THREAD

**Issue by iamjavademon** [dooboolab/flutter_inapp_purchase#49]

**Comment by dooboolab** [comment]
@lefoy I just found wrong `npe` in `android` during `getAvailablePurchases` and fixed it in `0.8.6`. Would you mind trying this out?

**Comment by dooboolab** [comment]
@iamjavademon  I just found wrong `npe` in `android` during `getAvailablePurchases` and fixed it in `0.8.6`. Would you mind trying this out?

**Comment by dooboolab** [comment]
@iamjavademon  Ah sorry, I wrote wong update on comment earlier so I deleted it. I think you this is right result because you can't restore the consumable product in android (correct me if I am wrong because I am sure in ios). Also, referred to [LINK](@iamjavademon  Ah sorry, I wrote wong ). If you find any other issue with this feel free to reopen.

**Comment by iamjavademon** [comment]
Sure will do so now.
    On Tuesday, December 4, 2018, 5:18:02 AM GMT+1, Hyo Chan Jang <notifications@github.com> wrote:  
 
 
@lefoy I just found wrong npe in android during getAvailablePurchases and fixed it in 0.8.6. Would you mind trying this out?
